proveedores/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from .views import proveedores_list, proveedores_registro, proveedores_info, marcar_retiro, estadisticas_proveedores, bodega_list, bodega_crear, estadisticas_bodegas, registro, iniciar_sesion, almacen_detail
#from . import views



urlpatterns = [
    path('', iniciar_sesion, name='login'),
    path('index/', proveedores_list, name='proveedores_list'),
    path('registro/', proveedores_registro, name='proveedores_registro'),
    path('info/', proveedores_info, name='proveedores_info'),
    path('retirar/<int:proveedor_id>/', marcar_retiro, name='marcar_retiro'),
    path('estadisticas/', estadisticas_proveedores, name='estadisticas_proveedores'),
    path('bodega/', bodega_crear, name='bodega_crear'),
    path('listabodega/', bodega_list, name='bodega_list'),
    path('estadisticas_bodega/', estadisticas_bodegas, name='estadisticas_bodegas'),
    path('registro_usuarios/', registro, name='registro'),
    path('login/', iniciar_sesion, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('almacen/<int:almacen_id>/', almacen_detail, name='almacen_detail'),  # Ruta dinámica para almacenes
]

sicoap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('proveedores.urls')),
]

proveedores/models.py
from django.contrib.auth.models import User
from django.db import models

#Modelo de almacenes
class Bodega(models.Model):
    tipo_bodega = models.CharField(max_length=45)
    nombre_responsable = models.CharField(max_length=45)
    
    def __str__(self) -> str:
        return self.tipo_bodega

#Modelo de proveedores
class Proveedor(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100, default='Apellido por defecto')
    rut = models.CharField(max_length=12)
    placa_patente = models.CharField(max_length=10)
    empresa = models.CharField(max_length=100)
    numero_contacto = models.CharField(max_length=15)
    fecha_ingreso = models.DateTimeField(auto_now_add=True)
    retirado = models.BooleanField(default=False)
    fecha_retiro = models.DateTimeField(null=True, blank=True)
    bodega = models.ForeignKey(Bodega, on_delete=models.SET_NULL, null=True, blank=True)
    

    def __str__(self):
        return self.nombre
    
#Modelo que vincula a los usuarios y crea roles    
class Perfil(models.Model):
    ROLES = [
        ('vigilante', 'Vigilante'),
        ('supervisor', 'Supervisor'),
    ]
    
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    rol = models.CharField(max_length=10, choices=ROLES)

    def __str__(self):
        return f'{self.usuario.username} - {self.rol}'    

proveedores/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Proveedor, Bodega, Perfil
import datetime

#Formulario de registro de proveedores
class ProveedorForm(forms.ModelForm):
    class Meta:
        model = Proveedor
        fields = ['nombre', 'apellido', 'rut', 'empresa', 'placa_patente', 'numero_contacto', 'bodega']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'nombre', 'placeholder': 'Escriba Nombre del proveedor'}),
            'apellido': forms.TextInput(attrs={'class': 'apellido', 'placeholder': 'Escriba Apellido del proveedor'}),
            'rut': forms.TextInput(attrs={'class': 'rut', 'placeholder': 'Escriba Rut del proveedor'}),
            'empresa': forms.TextInput(attrs={'class': 'empresa', 'placeholder': 'Ingrese nombre de la Empresa'}),
            'placa_patente': forms.TextInput(attrs={'class': 'placa_patente', 'placeholder': 'Ingrese Placa Patente del Vehículo'}),
            'numero_contacto': forms.TextInput(attrs={'class': 'numero_contacto', 'placeholder': 'Ingrese número de contacto'}),
            'bodega': forms.Select(attrs={'class': 'form-control'}),
        }
    
    #Normalizar datos
    def clean_nombre(self):
        nombre = self.cleaned_data.get('nombre')
        return nombre.strip().title() # Eliminar espacios y capitalizar cada palabra
    
    def clean_apellido(self):
        apellido = self.cleaned_data.get('apellido')
        return apellido.strip().title() # Eliminar espacios y capitalizar cada palabra
    
    def clean_empresa(self):
        empresa = self.cleaned_data.get('empresa')
        return empresa.strip().upper()  # Eliminar espacios y convertir a mayúsculas
    
    def clean_rut(self):
        rut = self.cleaned_data.get('rut')
        return rut.replace('.', '').replace('-', '').upper()  # Eliminar puntos, guiones y convertir a mayúsculas

    def clean_placa_patente(self):
        placa_patente = self.cleaned_data.get('placa_patente')
        return placa_patente.replace('-', '').upper()  # Eliminar guiones y convertir a mayúsculas

    def clean_numero_contacto(self):
        numero_contacto = self.cleaned_data.get('numero_contacto')
        return ''.join(filter(str.isdigit, numero_contacto))  # Mantener solo dígitos


#Formulario para registrar Bodega
class BodegaForm(forms.ModelForm):
    class Meta:
        model = Bodega
        fields = ['tipo_bodega', 'nombre_responsable']
        widgets = {
            'tipo_bodega': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el tipo de bodega'}),
            'nombre_responsable': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el nombre del responsable'}),
        }

#Formulario para seleccionar mes        
class MonthSelectForm(forms.Form):
    month = forms.ChoiceField(
        choices=[(i, datetime.date(2008, i, 1).strftime('%B')) for i in range(1, 13)],
        label="Seleccione el Mes",
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    year = forms.ChoiceField(
        choices=[(year, year) for year in range(2024, datetime.date.today().year + 1)],
        label="Seleccione el Año",
        widget=forms.Select(attrs={'class': 'form-control'})
    )

#Formulario de Registro de Usuarios
class RegistroForm(forms.ModelForm):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput, label="Contraseña")
    password2 = forms.CharField(widget=forms.PasswordInput, label="Confirmar Contraseña")
    rol = forms.ChoiceField(choices=Perfil.ROLES)

    class Meta:
        model = User
        fields = ['username', 'password']

    # Verificar que las contraseñas coincidan
    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')

        if password and password2 and password != password2:
            raise forms.ValidationError("Las contraseñas no coinciden. Inténtelo de nuevo.")
        
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])  # Hash the password
        if commit:
            user.save()
            perfil = Perfil.objects.create(usuario=user, rol=self.cleaned_data['rol'])
        return user

proveedores/views.py
from rest_framework import viewsets
from .models import Proveedor, Bodega
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Count
from django.db.models.functions import TruncMonth
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from .decorators import solo_supervisores
from django.utils import timezone
from .forms import ProveedorForm, BodegaForm, MonthSelectForm, RegistroForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required  
def proveedores_list(request):
    proveedores = Proveedor.objects.filter(retirado=False)
    numero_proveedores_activos = Proveedor.objects.filter(retirado=False).count()
    return render(request, 'index.html', {'proveedores': proveedores , 'numero_proveedores_activos': numero_proveedores_activos})


@login_required
def proveedores_info(request):
    proveedores = Proveedor.objects.all()
    return render(request, 'info.html', {'proveedores': proveedores})

@login_required
def proveedores_registro(request):
    #Registra a los proveedores
    if request.method == 'POST':
        form = ProveedorForm(request.POST)
        if form.is_valid():
            proveedor = form.save(commit=False)
            bodega_id = request.POST.get('bodega')
            if bodega_id:
                proveedor.bodega = Bodega.objects.get(id=bodega_id)
            print(proveedor.nombre, proveedor.apellido, proveedor.rut, proveedor.empresa, proveedor.placa_patente, proveedor.numero_contacto)
            messages.success(request, f'Proveedor {proveedor.nombre} ha sido registrado con éxito en el almacén.')
            proveedor.save()
            return redirect('proveedores_list')  # Redirige a la lista de proveedores después de guardar   
        else:
            print(form.errors)
    else:
        form = ProveedorForm()
    bodegas = Bodega.objects.all()
    return render(request, 'registro.html', {'form': form, 'bodegas': bodegas})

@login_required
def marcar_retiro(request, proveedor_id):
    #Retira a los provedores
    proveedor = Proveedor.objects.get(id=proveedor_id)
    proveedor.retirado = True
    proveedor.fecha_retiro = timezone.now()  # Registra la hora actual
    proveedor.save()
    return redirect('proveedores_list')  # Redirige al listado de proveedores

@solo_supervisores 
@login_required
def estadisticas_proveedores(request):
    # Contar la cantidad de proveedores registrados por mes
    proveedores_por_mes = (
        Proveedor.objects.annotate(month=TruncMonth('fecha_ingreso'))
        .values('month')
        .annotate(count=Count('id'))
        .order_by('month')
    )
    
    # Pasar los datos a la plantilla
    context = {
        'proveedores_por_mes': proveedores_por_mes,
    }
    return render(request, 'estadisticas.html', context)

@login_required
@solo_supervisores
def bodega_list(request):
    bodegas = Bodega.objects.all()
    return render(request, 'listabodega.html', {'bodegas': bodegas})

@login_required
@solo_supervisores
def bodega_crear(request):
    if request.method == 'POST':
        form = BodegaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('bodega_list')
        else:
            print(form.errors)
    else:
        form = BodegaForm()
    return render(request, 'bodega.html', {'form': form})

@login_required
@solo_supervisores
def estadisticas_bodegas(request):
    form = MonthSelectForm(request.GET or None)
    proveedores = Proveedor.objects.all()

    # Filtrar por mes y año
    if form.is_valid():
        month = int(form.cleaned_data['month'])
        year = int(form.cleaned_data['year'])
        proveedores = proveedores.filter(
            fecha_ingreso__year=year,
            fecha_ingreso__month=month
        )

    # Contar las visitas por bodega
    visitas_bodegas = proveedores.values('bodega__tipo_bodega').annotate(visitas=Count('bodega')).order_by('-visitas')

    return render(request, 'estadisticas_bodega.html', {
        'form': form,
        'visitas_bodegas': visitas_bodegas,
    })

#@login_required
#@solo_supervisores
def registro(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            user = form.save()
            print(f'Usuario creado: {user.username}')
            return redirect('login')
        else:
            print(f'Errores del formulario: {form.errors}')
    else:
        form = RegistroForm()
    return render(request, 'registro_usuario.html', {'form': form})


def iniciar_sesion(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('proveedores_list')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})



# Vista para mostrar el almacén y solo los proveedores que no se han retirado
def almacen_detail(request, almacen_id):
    almacen = get_object_or_404(Bodega, id=almacen_id)
    
    # Filtrar los proveedores que están asignados al almacén y no han sido retirados
    proveedores_activos = Proveedor.objects.filter(bodega=almacen, retirado=False)
    
    context = {
        'almacen': almacen,
        'proveedores': proveedores_activos  # Solo mostrar los proveedores activos
    }
    
    return render(request, 'almacen_detail.html', context)

proveedores/templates/almacen_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ almacen.tipo_bodega }} - Detalles</title>
    <meta http-equiv="refresh" content="30">
    <script>
        window.onload = function() {
            // Verifica si la API de síntesis de voz está disponible
            if ('speechSynthesis' in window) {
                {% if messages %}
                    {% for message in messages %}
                        var utterance = new SpeechSynthesisUtterance("{{ message }}");
                        speechSynthesis.speak(utterance);
                    {% endfor %}
                {% endif %}
            } else {
                console.log("La API de síntesis de voz no está soportada en este navegador.");
            }
        };
    </script>
</head>
<body>
    <h1>Almacén: {{ almacen.tipo_bodega }}</h1>
    <p>Responsable: {{ almacen.nombre_responsable }}</p>
    
    <h2>Proveedores Actuales en el Almacén</h2>
    <ul>
        {% for proveedor in proveedores %}
            <li>{{ proveedor.nombre }} {{ proveedor.apellido }} - Empresa: {{ proveedor.empresa }}</li>
        {% empty %}
            <li>No hay proveedores actualmente en este almacén.</li>
        {% endfor %}
    </ul>
</body>
</html>

proveedores/templates/bodega.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SICOAP | Bodegas</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/summernote/summernote-bs4.min.css' %}">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/index" class="nav-link">Inicio</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/registro" class="nav-link">Registro</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/info" class="nav-link">Información</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/estadisticas" class="nav-link">Estadísticas de Proveedores</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/bodega" class="nav-link">Registrar Bodega</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/listabodega" class="nav-link">Lista de Bodegas</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/estadisticas_bodega" class="nav-link">Estadísticas de Bodegas</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        {% if user.is_authenticated %}
          <a href="{% url 'logout' %}" class="nav-link">Cerrar sesión</a>
        {% endif %}
      </li>
    </ul>    
  </nav>
  <!-- /.navbar -->

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Bodegas del Hospital</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/index">Inicio</a></li>
              <li class="breadcrumb-item active">Bodegas</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      
      <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">  
              <div class="card">
                <div class="card-header">
                  <h3 class="card-title">Registro de nueva bodega</h3>
                </div>

                <form method="POST" action="{% url 'bodega_crear' %}">
                  {% csrf_token %}
                  <div class="card-body">
                    <div class="form-group">
                      <label for="{{form.id_tipo_bodega}}">Nombre de la nueva Bodega</label>
                      {{form.id_tipo_bodega}}
                      <input type="text" name="tipo_bodega" class="form-control tipo_bodega" id="id_tipo_bodega" placeholder="Escriba el nombre de la nueva Bodega">

                    </div>
                    
                    <div class="form-group">
                      <label for="id_nombre_responsable">Nombre del responsable de la Bodega</label>
                      <input type="text" name="nombre_responsable" class="form-control" id="id_nombre_responsable" placeholder="Escriba el Nombre y el apellido del responsable de la Bodega">
                    </div>
                  </div>
                  <!-- /.card-body -->
                  <div class="card-footer">
                    <button type="submit" class="btn btn-block btn-info btn-lg">Registrar nueva Bodega</button>
                    <a href="{% url 'bodega_crear' %}" class="btn btn-block btn-danger btn-lg">Cancelar</a>
                  </div>

                </form>

              </div>
            </div>  
          </div>
        </div>    
      </div>  



          <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="/index" class="brand-link">
              <img src="{% static 'lib/adminlte-3.2.0/dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
              <span class="brand-text font-weight-light">SICOAP</span>
            </a>
        
            <!-- Sidebar -->
            <div class="sidebar os-host os-theme-light os-host-overflow os-host-overflow-y os-host-resize-disabled os-host-scrollbar-horizontal-hidden os-host-transition"><div class="os-resize-observer-host observed"><div class="os-resize-observer" style="left: 0px; right: auto;"></div></div><div class="os-size-auto-observer observed" style="height: calc(100% + 1px); float: left;"><div class="os-resize-observer"></div></div><div class="os-content-glue" style="margin: 0px -8px; width: 249px; height: 898px;"></div><div class="os-padding"><div class="os-viewport os-viewport-native-scrollbars-invisible" style="overflow-y: scroll;"><div class="os-content" style="padding: 0px 8px; height: 100%; width: 100%;">
              <!-- Sidebar user panel (optional) -->
              <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                  <img src="{% static 'lib/adminlte-3.2.0/dist/img/user8-128x128.jpg' %}" class="img-circle elevation-2" alt="User Image">
                </div>
                <div class="info">
                  <a href="#" class="d-block">{{ user.username }}</a>
                </div>
              </div>
        
              <!-- Sidebar Menu -->
              <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                  <!-- Add icons to the links using the .nav-icon class
                       with font-awesome or any other icon font library -->
                  <li class="nav-item">
                    <a href="/index" class="nav-link">
                      <i class="nav-icon fas fa-tachometer-alt"></i>
                      <p>
                        Dashboard                            
                      </p>
                    </a>
                  </li>


                  <li class="nav-item">
                    <a href="/registro" class="nav-link">
                      <i class="nav-icon fas fa-edit"></i>
                      <p>
                        Registro del Proveedor                        
                      </p>
                    </a>
                  </li>
                      
                  <li class="nav-item">
                    <a href="/info" class="nav-link">
                      <i class="nav-icon fas fa-search"></i>
                      <p>
                        Información Proveedores                            
                      </p>
                    </a>
                  </li>
                  
                  <li class="nav-header">ESTADÍSTICAS DE BODEGAS</li>
                  <li class="nav-item">
                    <a href="/estadisticas" class="nav-link">
                      <i class="nav-icon fas fa-chart-pie"></i>
                      <p>
                        Estadísticas de Proveedores                            
                      </p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="/estadisticas_bodega" class="nav-link">
                      <i class="nav-icon fas fa-chart-pie"></i>
                      <p>
                        Estadísticas de Bodegas                            
                      </p>
                    </a>
                  </li>

                  <li class="nav-header">ADMINISTRACIÓN</li>
                  
                  <li class="nav-item">
                    <a href="/bodega" class="nav-link active">
                      <i class="nav-icon fas fa-warehouse"></i>
                      <p>
                        Registrar Bodega                            
                      </p>
                    </a>
                  </li>

                  <li class="nav-item">
                    <a href="/listabodega" class="nav-link">
                      <i class="nav-icon fas fa-warehouse"></i>
                      <p>
                        Lista de Bodegas                            
                      </p>
                    </a>
                  </li>

                  <li class="nav-item">
                    <a href="/registro_usuarios" class="nav-link">
                      <i class="nav-icon fas fa-edit"></i>
                      <p>
                        Registro de Nuevo Usuario                           
                      </p>
                    </a>
                  </li>

                </ul>
              </nav>
              <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
          </aside>
    </section>
  </div>
  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 1.0
    </div>
    <strong>Software Desarrollado por Ricardo Parada</a>.</strong> All rights reserved.
  </footer>       
</div>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

<!-- jQuery -->
<script src="{% static 'lib/adminlte-3.2.0/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'lib/adminlte-3.2.0/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'lib/adminlte-3.2.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'lib/adminlte-3.2.0/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'lib/adminlte-3.2.0/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'lib/adminlte-3.2.0/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'lib/adminlte-3.2.0/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'lib/adminlte-3.2.0/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'lib/adminlte-3.2.0/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'lib/adminlte-3.2.0/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'lib/adminlte-3.2.0/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'lib/adminlte-3.2.0/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'lib/adminlte-3.2.0/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'lib/adminlte-3.2.0/dist/js/adminlte.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'lib/adminlte-3.2.0/dist/js/pages/dashboard.js' %}"></script>
</body>
</html>